export const ONTOLOGY = {
  entities: [
    {
      id: "project",
      name: "Project",
      aliases: [
        "project",
        "project_name",
        "name_of_project",
        "name_of_ongoing_work",
        "name_of_project.",
      ],
    },
    {
      id: "state",
      name: "State/UT",
      aliases: ["state", "state-wise", "state_assigned", "state/ut", "states/ut"],
    },
    {
      id: "district",
      name: "District",
      aliases: ["district", "name_of_districts_invloved"],
    },
    {
      id: "segment",
      name: "Segment",
      aliases: ["segment_id"],
    },
    {
      id: "date",
      name: "Year/Time",
      aliases: ["year", "financial_year", "year-wise", "observation_year", "observation_month", "period_start", "period_end", "data_as_of"],
    },
    {
      id: "corridor",
      name: "Corridor",
      aliases: ["corridor", "corridor_id", "stretch/_package_name", "nh_number"],
    },
    { id: "agency", name: "Implementing / reporting agency", aliases: ["agency", "implementing_agency"] },
    { id: "asset_entity", name: "Financial / asset entity", aliases: ["entity_id", "entity_type", "entity_name"] },
    { id: "road_class", name: "Road classification", aliases: ["road_class"] },
  ],
  metric_dimensions: ["metric", "unit", "original_unit", "estimate_type", "statement_basis", "period_basis", "evidence_class"],
  relations: [
    { from: "asset_entity", to: "agency", name: "reported_by", rationale: "Financial and asset observations retain their reporting agency without inferring ownership from geography." },
    { from: "asset_entity", to: "road_class", name: "classified_as", rationale: "NH, SH and state expressways are explicit source classifications." },
    { from: "asset_entity", to: "date", name: "observed_for_period", rationale: "Financial facts retain reporting periods and observation cutoffs." },
    {
      from: "project",
      to: "state",
      name: "located_in / implemented_in",
      rationale: "Project-level and state-level feeds carry explicit location keys.",
    },
    {
      from: "project",
      to: "district",
      name: "implemented_in_district",
      rationale: "Some project lists are district-scoped with project descriptors.",
    },
    {
      from: "segment",
      to: "state",
      name: "assigned_model_geography",
      rationale: "Synthetic segment geography is a scenario assignment, not an observed asset location.",
    },
    {
      from: "project",
      to: "date",
      name: "planned_or_reported_at",
      rationale: "Finance, construction and model rows carry year-level observations.",
    },
  ],
  provenance_rules: {
    official_measured: "Validated observations from government publications with document/table/page lineage; document presence alone is not measured evidence.",
    issuer_disclosed: "Issuer and corporation disclosures, with standalone/consolidated basis and period retained; valuations and forecasts remain labelled.",
    proxy_derived: "OpenStreetMap and other proxy signals used only as context; synthetic data belongs to model output.",
    model_output: "Scenario, risk and access projections generated by model passes, not policy facts.",
  },
};

const ENTITY_ALIASES = ONTOLOGY.entities.flatMap((e) =>
  e.aliases.map((alias) => ({ entityId: e.id, alias: alias.toLowerCase() }))
);

function hasColumn(entry, alias) {
  const manifest = entry?.manifest || {};
  const columns = Array.isArray(manifest?.columns) ? manifest.columns : [];
  const title = String(entry?.source?.title || entry?.source_id || "").toLowerCase();
  const datasetTitle = String(entry?.dataset_source || "").toLowerCase();
  const all = new Set([
    ...columns.map((c) => String(c).toLowerCase()),
    title,
    datasetTitle,
    String(entry?.source_id || "").toLowerCase(),
  ]);
  return all.has(alias.toLowerCase());
}

export function inferOntologyCoverage(catalog) {
  const entries = Object.values(catalog || {}).filter((entry) => entry.analytical_ready !== false || entry.disclosure_ready === true);
  const counts = {};
  ONTOLOGY.entities.forEach((entity) => {
    const matched = entries.filter((entry) => {
      return ENTITY_ALIASES.some((probe) => probe.entityId === entity.id && hasColumn(entry, probe.alias));
    });
    counts[entity.id] = matched.length;
  });

  const relationCoverage = ONTOLOGY.relations.map((relation) => {
    const fromCols = ENTITY_ALIASES.filter((alias) => alias.entityId === relation.from).map((x) => x.alias);
    const toCols = ENTITY_ALIASES.filter((alias) => alias.entityId === relation.to).map((x) => x.alias);
    const supporting = entries.filter((entry) => {
      return (
        ENTITY_ALIASES.some((probe) => probe.entityId === relation.from && hasColumn(entry, probe.alias)) &&
        ENTITY_ALIASES.some((probe) => probe.entityId === relation.to && hasColumn(entry, probe.alias))
      );
    });
    return {
      ...relation,
      evidence_count: supporting.length,
      supporting_sources: supporting.map((entry) => entry.source_id).filter(Boolean),
    };
  });

  return {
    entityCounts: counts,
    relationCoverage,
  };
}
